MANIFEST.in
ui/craco.config.js
ui/package-lock.json
ui/package.json
ui/public/logo-invenio-ils.svg
ui/src/config.js
ui/src/index.js
ui/src/overridableMapping.js
ui/src/overriden/components/Footer/Footer.js
ui/src/overriden/components/Menu/RightMenuItem.js
ui/src/overriden/frontsite/Home/Home.js
ui/src/overriden/frontsite/Home/Slogan.js
ui/src/semantic-ui/site/collections/menu.variables
ui/src/semantic-ui/site/elements/container.overrides
ui/src/semantic-ui/site/globals/site.variables
ui/src/semantic-ui/site/views/card.overrides

closes #101
- Remove `popular topics`,  `our services` and section
- Customize footer 
- Change header to CERN library catalogue instead of Integrated library system
- Add Quick access menu in navigation bar 
- Change order of sections  
- Change background image minimum height to 65vh
- Remove purple color override
- Display max 5 books in each section
- Mobile view works correctly for homepage
**Screenshots**
Quick Access menu:
Sections + Footer:

ui: customize homepage

---

ui/src/overridableMapping.js
ui/src/overridden/frontsite/DocumentRequest/DocumentRequestForm.js

* Overrides the payment information field to display
a placeholder `Insert budget code if applicable`
* closes #118
react-invenio-app-ils: https://github.com/inveniosoftware/react-invenio-app-ils/pull/114

docreq: Overrides document request form

---

cds_ils/config.py
ui/src/config.js

* Remove `legacy_name` of accelerators
from data model extensions
* closes #120

config: Update data model extensions

---

ui/package.json
ui/src/overridableMapping.js
ui/src/overridden/backoffice/PatronMetadata/PatronMetadata.js

- NEW enable https
- NEW metadata table for CERN specific patron details
- NEW patron details action menu for metadata
- closes #145

patron: CERN specific metadata

---

cds_ils/cli.py
cds_ils/static_pages/about.html
cds_ils/static_pages/contact.html
cds_ils/static_pages/faq.html
cds_ils/static_pages/terms.html
ui/package.json
ui/src/config.js
ui/src/overridden/components/Footer/Footer.js
ui/src/overridden/components/Menu/RightMenuItem.js

Remove emails around and use only the `contact` page with clear instructions on who/how to contact:
Needs release of `react-invenio-app-ils` with [this PR](https://github.com/inveniosoftware/react-invenio-app-ils/pull/251) merged.

rework footer and contacts

---

cds_ils/cli.py

Ongoing loan for user testing is now ending 3 days after today date so that extension option will be enabled.

Cli: fix unavailable extension for user test loan

---

cds_ils/literature/serializers/json.py

Covers were displaying the Placeholder because the field `metadata.cover_metada.urls` was not present and in that case it will show the Placeholder component. 
Added to the serializer the missing field.

covers: Fixes covers bug

---

cds_ils/config.py
cds_ils/ldap/api.py
cds_ils/patrons/indexer.py
tests/api/test_indexing.py
tests/conftest.py
tests/ldap/test_ldap.py

- override `reindex_patrons` function with function that also checks if user has a remote account
- add configuration to whether local accounts should be indexed or not
Depends on inveniosoftware/invenio-app-ils#1012
Closes #246

patrons: index patrons only if they have remote account

---

cds_ils/importer/providers/cds/rules/base.py
cds_ils/migrator/acquisition/orders.py
cds_ils/migrator/document_requests/api.py
cds_ils/migrator/items/api.py
cds_ils/migrator/items/utils.py
cds_ils/migrator/patrons/api.py
scripts/life_data_setup
scripts/setup
tests/migrator/test_books.py

fixed problem:
the cancel reasons were quite random, while the ones we have are controlled
I moved the library notes to internal note field(https://github.com/inveniosoftware/invenio-app-ils/pull/1013), but the question is do we actually need it ?

migration: fix import document requests

---

MANIFEST.in
cds_ils/config.py
requirements.pinned.txt
scripts/celery

- bump invenio-oauthclient to fix authentication
- split server and celery scripts

global: fix login on CERN QA Auth

---

cds_ils/importer/providers/cds/cds.py
cds_ils/importer/providers/cds/models/document.py
cds_ils/importer/providers/cds/models/journal.py
cds_ils/importer/providers/cds/models/multipart.py
cds_ils/importer/providers/cds/models/standard.py
cds_ils/importer/providers/cds/rules/base.py
cds_ils/importer/providers/cds/rules/journal.py
scripts/bootstrap
tests/migrator/test_books.py
tests/migrator/test_series.py
tests/migrator/test_standard.py

* Adds ignore rule for document type
* Fixes agency_code bug, it was preventing the records indexing
* Fixes _migration bug, there where some missing fields who caused 'NoneType' error
* closes #https://github.com/CERNDocumentServer/cds-ils/issues/308
ignored rules requested in https://cernbox.cern.ch/index.php/apps/onlyoffice/edit/__myprojects/digital-repositories/Services_Projects/CDS/CDS-ILS/CDS%20-%20Library%20shared/missing-rules-values-journals.xlsx

migration: journal fixes

---

cds_ils/cli.py
cds_ils/importer/series/importer.py
cds_ils/patrons/serializers.py
cds_ils/patrons/views.py

* Replaces execute() from ES querys capable of
returning more than 10 hits with scan()
* closes https://github.com/inveniosoftware/invenio-app-ils/issues/1048

ES: replaces execute()

---

cds_ils/importer/providers/cds/ignore_fields.py
cds_ils/importer/providers/cds/models/journal.py
cds_ils/importer/providers/cds/rules/base.py
tests/migrator/rules/test_books.py

* Adds constraints for conference rule
* Blocked by https://github.com/CERNDocumentServer/cds-ils/pull/375
* closes https://github.com/CERNDocumentServer/cds-migrator-kit/issues/80
* closes https://github.com/CERNDocumentServer/cds-migrator-kit/issues/65

rules: conference and alternative_title

---

ui/src/Importer/ImporterTaskDetails/ImportedDocuments.js
ui/src/overridableMapping.js
ui/src/overridden/frontsite/Document/DocumentDetails/DocumentPanel/StandardNumber.js
ui/src/semantic-ui/site/elements/label.overrides

Depends on https://github.com/inveniosoftware/react-invenio-app-ils/pull/410
Multiple values that don't fit in the same line:
Multiple values that fit in the same line:
Mobile:

ui: display standard number in an prominent place

---

cds_ils/importer/providers/cds/ignore_fields.py
cds_ils/importer/providers/cds/rules/base.py
cds_ils/importer/providers/cds/rules/standard.py
tests/migrator/rules/test_books.py
tests/migrator/rules/test_standard.py

* Ignores field 962__ except for standards
* closes https://github.com/CERNDocumentServer/cds-migrator-kit/issues/88

migration: standards

---

ui/src/overridableMapping.js
ui/src/overridden/frontsite/DocumentSearch/StandardCardView.js
ui/src/overridden/frontsite/DocumentSearch/StandardListView.js
ui/src/overridden/frontsite/LiteratureSearch/LiteratureSearch.js
ui/src/semantic-ui/site/elements/label.overrides

Depends on https://github.com/inveniosoftware/react-invenio-app-ils/pull/417
- display standard number in card and list view search results
List view
Card view (display only first standard number if multiple)

[BLOCKED]ui: display standard number in search results

---

cds_ils/static_pages/search_guide.html

Include the proper references in the pre-filled search queries of the search guide.
closes: https://github.com/CERNDocumentServer/cds-ils/issues/575

SearchGuide: fix search guide links

---

cds_ils/config.py
cds_ils/templates/invenio_app_ils_circulation/notifications/cds_bulk_extend.html

Set the subject of the emails sent when performing a bulk extend.
Fix cds bulk extend template not overwritting ils.
closes: https://github.com/CERNDocumentServer/cds-ils/issues/626

BulkExtend: change email subject 

---

cds_ils/importer/documents/importer.py
cds_ils/importer/importer.py
setup.py
ui/src/importer/importerTaskDetails/ImportedDocumentReport.js

The title from the parsed XML file is now being used instead of the title of the matched document. Now also checks if the title is equal to the matched document to further prevent wrongful matches 
closes https://github.com/CERNDocumentServer/cds-ils/issues/613

Importer: displayed title from raw_json and added title check in addition to isbn check

---

cds_ils/importer/api.py
cds_ils/importer/errors.py
cds_ils/importer/importer.py
ui/src/config.js
ui/src/importer/EitemImportDetailsModal/EitemImportDetailsModal.js
ui/src/importer/Importer.js
ui/src/importer/ImporterList.js
ui/src/importer/importerTaskDetails/ImportedDocuments.js
ui/src/importer/importerTaskDetails/ImporterTaskDetailsComponents/ImportStats.js
ui/src/importer/importerTaskDetails/ImporterTaskDetailsComponents/ImporterDateLabel.js
ui/src/importer/importerTaskDetails/ImporterTaskDetailsComponents/ImporterFilenameLabel.js
ui/src/importer/importerTaskDetails/ImporterTaskDetailsComponents/ImporterProviderLabel.js
ui/src/importer/importerTaskDetails/ImporterTaskDetailsComponents/ImporterReportMode.js
ui/src/importer/importerTaskDetails/ImporterTaskDetailsComponents/ImporterReportStatusLabel.js
ui/src/semantic-ui/site/views/statistic.overrides

Allow un-tick 'Ignore missing rules'.
Remove linter warnings from the code.
Remove the , from the dates.
Display name of the uploaded file (in imports list).
Display name of the uploaded file (in import details).
Display date of the import (in imports details).
Display provider of the import (in imports list).
Add a statistic/filter to partial matches.
Fix pagination in import details.
Set the displayed names of the providers.
Ensure statistics are displayed in one row.
Rework import details page layout.
Raise an error when wrong importer is specified.
closes https://github.com/CERNDocumentServer/cds-ils/issues/611

Importer: add pagination to imports list

---

cds_ils/circulation/indexer.py
cds_ils/circulation/serializers/__init__.py
cds_ils/config.py
cds_ils/ext.py
ui/src/importer/ImporterList.js

* This change only affects elastic search.
* The first item is the first of the associated document.
* Allow removing fields from the loan serializer.
* Closes CERNDocumentServer/cds-ils#499
* Improves: https://github.com/CERNDocumentServer/cds-ils/pull/676

Circulation: add to each loan the first item on shelf

---

cds_ils/vocabularies/data/alternative_identifier_schemes.json
cds_ils/vocabularies/data/identifier_schemes.json
ui/package-lock.json
ui/package.json
ui/src/overridableMapping.js
ui/src/overridden/frontsite/Document/DocumentDetails/DocumentCirculation/LiteratureKeyword.js
ui/src/overridden/frontsite/Document/DocumentDetails/DocumentMetadataTabs/DocumentConference.js
ui/src/overridden/frontsite/Document/DocumentDetails/DocumentMetadataTabs/Identifiers/Identifiers.js
ui/src/overridden/frontsite/Document/DocumentDetails/DocumentMetadataTabs/Identifiers/actions.js
ui/src/overridden/frontsite/Document/DocumentDetails/DocumentMetadataTabs/Identifiers/index.js
ui/src/overridden/frontsite/Document/DocumentDetails/DocumentMetadataTabs/Identifiers/reducer.js
ui/src/overridden/frontsite/DocumentRequest/DocumentRequestFormHeader.js
ui/src/reducers.js

Added a extra clarification message on the document request from in the front-site and also added some vocabulary fields to identifiers to make them clickable.
DESKTOP -> 
MOBILE -> 
closes https://github.com/CERNDocumentServer/cds-ils/issues/526
depends on https://github.com/inveniosoftware/react-invenio-app-ils/pull/515

[DEPENDS]Vocab/doc request: added message and fields

---

cds_ils/importer/documents/importer.py
tests/importer/data/existing_documents.json
tests/importer/data/match_testing_documents.json
tests/importer/test_document_matching.py

* remove incorrect matching based on provider ids
* closes https://cern.service-now.com/nav_to.do?uri=u_request_fulfillment.do?sys_id=d682586a1b8d8110e823a71eab4bcb4a

importer: validate provider identifiers

---

cds_ils/importer/views.py
setup.py

* throw 404 error manually for non existing task
* closes https://github.com/CERNDocumentServer/cds-ils/issues/759
"Pretty" 404 error page displaying preview:

importer details: non existing task page

---

ui/src/overridableMapping.js
ui/src/overridden/frontsite/OpeningHours/OpeningHoursDetails.js

Closes: https://github.com/CERNDocumentServer/cds-ils/issues/353

ui: frontsite: Update Overridable opening hours header and details component

---

cds_ils/importer/handlers.py
ui/src/importer/importerTaskDetails/ImporterTaskDetailsComponents/ImportedTable.js

importer: Rename Output->Related Document and link doc for errored rows

---

ui/src/overridden/components/Footer/Footer.js
ui/src/overridden/components/Menu/RightMenuItem.js
ui/src/overridden/frontsite/DocumentRequest/DocumentRequestFormHeader.js

ui: improve request page text

---

cds_ils/importer/series/importer.py
tests/importer/data/match_testing_series.json
tests/importer/test_series_matching.py

importer: Update series importer to clean series/ser from title

---

cds_ils/importer/eitems/importer.py
cds_ils/importer/providers/cds/importer.py
cds_ils/importer/providers/cds/rules/base.py
cds_ils/importer/providers/cds/rules/multipart.py
cds_ils/vocabularies/data/eitem_sources.json
tests/migrator/rules/test_books.py
tests/migrator/rules/test_series.py

importer: cds: Don't make CDS E-Items open access

---

ui/package-lock.json
ui/package.json
ui/src/overridableMapping.js
ui/src/overridden/backoffice/Document/DocumentDetails/DocumentItems.js
ui/src/overridden/backoffice/Items/ItemCirculationShelf.js

overridden: backoffice: Display call number for items

---

cds_ils/cli.py
cds_ils/config.py
cds_ils/ldap/client.py
cds_ils/ldap/user_importer.py
cds_ils/ldap/utils.py
cds_ils/oauth.py
tests/conftest.py
tests/ldap/test_ldap.py

LDAP: Update user names formatting on sync

---

.github/workflows/tests.yml
cds_ils/config.py
run-tests.sh
setup.cfg
tests/api/test_documents_search.py
tests/conftest.py
tests/migrator/rules/test_books.py
tests/migrator/rules/test_journals.py
tests/migrator/rules/test_series.py
tests/migrator/rules/test_standard.py
tests/migrator/test_fields_utils.py

Original issue:
- Book cannot be found: https://catalogue.library.cern/literature/0s8wv-bxz77
- Query: https://catalogue.library.cern/search?q=quantum%20field%20theory%20schwartz&l=grid&order=asc&p=1&s=15&sort=bestmatch
- NEEDS https://github.com/inveniosoftware/invenio-app-ils/pull/1221

search: enable AND operator and cross_field

---

cds_ils/patrons/permissions.py

Requires:
- https://github.com/inveniosoftware/react-invenio-app-ils/pull/646
- https://github.com/inveniosoftware/invenio-app-ils/pull/1222

permissions: move self-checkout to invenio-app-ils

---

cds_ils/importer/XMLRecordToJson.py
cds_ils/importer/errors.py
tests/importer/data/safari_audiobook2.xml
tests/importer/data/safari_record_broken_mediatype.xml
tests/importer/test_safari_dojson.py

* closes https://github.com/CERNDocumentServer/cds-ils/issues/921

importer: handle different import media types
