CERNDocumentServer/cds-ils

.travis.yml
cds_books/config.py
ui/src/config.js
ui/src/index.js

- depends on inveniosoftware/invenio-app-ils#878
- closes #98

config: document extended metadata

---

cds_books/literature/covers.py
cds_books/migrator/api.py
cds_books/migrator/records.py

migration: schema update fixes

---

cds_books/ldap/api.py
tests/ldap/test_ldap_cli.py
ui/src/config.js
ui/src/overridden/components/Footer/Footer.js
ui/src/overridden/components/Menu/RightMenuItem.js

- updated config to match react-invenio-app-ils
- fixed getStaticPageByName to match signature
- removed a couple of unused imports

config: updated to match newest layout

---

Pipfile
Pipfile.lock
ui/package-lock.json
ui/package.json
ui/src/overridableMapping.js
ui/src/overridden/backoffice/DeliveryIcon/DeliveryIcon.js

Closes #30 
Loans search page:
Loan details page:
Checkout book notification:

Backoffice: Display icon for delivery method in loans

---

cds_books/cli.py
cds_books/config.py
cds_books/ldap/admin.py
cds_books/ldap/api.py
cds_books/ldap/cli.py
cds_books/ldap/models.py
cds_books/ldap/tasks.py
cds_books/ldap/templates/cds_books_admin/create_task.html
setup.py
tests/ldap/test_ldap_cli.py

* refactored the ldap user synchronization function
* new database model to store synchronization task logs
* includes an invenio admin view
* json structured messages in logger
* closes #59

ldap: users synchronization enhancements

---

.travis.yml
cds_ils/config.py
ui/src/config.js

* standard_CERN_status -> standard_review
* accelerators_experiments -> unit
* closes #121

rename: Rename extension fields names

---

cds_ils/config.py
cds_ils/literature/covers.py
cds_ils/literature/tasks.py
tests/api/test_literature_covers.py

Problems:
- When a change happens in the identifiers of a document, it might need to refresh the page to see the change in the cover.
Closes #110

ui: fix placeholder bug

---

cds_ils/__init__.py
cds_ils/cli.py
cds_ils/config.py
cds_ils/ldap/admin.py
cds_ils/ldap/models.py
cds_ils/migrator/api.py
cds_ils/migrator/cli.py
cds_ils/migrator/errors.py
cds_ils/migrator/handlers.py
cds_ils/migrator/records.py
cds_ils/migrator/utils.py
cds_ils/patrons/api.py
cds_ils/patrons/permissions.py
cds_ils/patrons/serializers.py
cds_ils/theme/__init__.py
cds_ils/theme/webpack.py
requirements.pinned.txt
scripts/life_data_setup
ui/package.json

closes #136
the screenshots available in the Weekly recap, I didn't add them because of user data protection ;)

migrator: ingest loans and user extra data

---

cds_ils/config.py
cds_ils/templates/cds_ils/login_user.html
scripts/server

* enables SSO login in the backend (Invenio-Admin)
* override login template to remove local logins
* disable local login registration
* remove hardcoded Syndetic Client ID

global: fix config for oauth

---

cds_ils/migrator/api.py
cds_ils/migrator/documents/api.py
cds_ils/migrator/eitems/api.py
cds_ils/migrator/errors.py
cds_ils/migrator/records.py

migrator: file checksum verification

---

cds_ils/cli.py
cds_ils/static_pages/about.html
cds_ils/static_pages/faq.html
cds_ils/static_pages/terms.html

StaticPages: add content for static pages

---

cds_ils/cli.py
cds_ils/vocabularies/__init__.py
cds_ils/vocabularies/data/__init__.py
cds_ils/vocabularies/data/acq_order_line_mediums.json
cds_ils/vocabularies/data/acq_order_line_payment_modes.json
cds_ils/vocabularies/data/acq_order_line_purchase_types.json
cds_ils/vocabularies/data/acq_order_line_recipients.json
cds_ils/vocabularies/data/acq_payment_modes.json
cds_ils/vocabularies/data/alternative_identifier_schemes.json
cds_ils/vocabularies/data/alternative_title_types.json
cds_ils/vocabularies/data/author_affiliation_identifier_schemes.json
cds_ils/vocabularies/data/author_identifier_schemes.json
cds_ils/vocabularies/data/author_roles.json
cds_ils/vocabularies/data/author_types.json
cds_ils/vocabularies/data/conference_countries.json
cds_ils/vocabularies/data/conference_identifier_schemes.json
cds_ils/vocabularies/data/currencies.json
cds_ils/vocabularies/data/docreq_payment_method.json
cds_ils/vocabularies/data/docreq_request_type.json
cds_ils/vocabularies/data/document_requests_mediums.json
cds_ils/vocabularies/data/identifier_schemes.json
cds_ils/vocabularies/data/ill_item_types.json
cds_ils/vocabularies/data/ill_payment_modes.json
cds_ils/vocabularies/data/languages.json
cds_ils/vocabularies/data/series_identifier_schemes.json
cds_ils/vocabularies/data/series_url_access_restrictions.json
cds_ils/vocabularies/data/tags.json
scripts/setup

vocabulary: Adds vocabularies

---

cds_ils/migrator/utils.py
scripts/life_data_setup

* change requested by the library

migration: change FOR_REFERENCE_ONLY item statuses

---

cds_ils/config.py
cds_ils/ldap/admin.py
cds_ils/ldap/api.py
cds_ils/ldap/cli.py
tests/ldap/test_ldap_cli.py

* refactors LDAP sync and import to avoid db session close after user
deletion
* change APP_ALLOWED_HOSTS config to be more secure
* change cron task to run overnight

ldap: fix + refactor sync users

---

cds_ils/cli.py
cds_ils/demo_data/documents.json
cds_ils/demo_data/items.json
cds_ils/demo_data/libraries.json
scripts/life_data_setup
setup.py

- `cds-ils demo import-demo-data --are-docs --path <path_to_json_file>` to add demo documents
- `cds-ils demo import-demo-data --are-items --path <path_to_json_file>` to add demo items
- `cds-ils demo user-test-prepare --user-email <user_email>` to add an ongoing loan for a user that starts 3 weeks before today and a past loan that started a year before today and has ended
- `cds-ils demo user-test-clean --user-email <user_email> --given-date <date>` to delete all loans and document requests made by the given user on a given date (default date=today)

Cli: commands to add books, items, loans and remove loans

---

cds_ils/config.py
cds_ils/vocabularies/data/document_accelerators.json
cds_ils/vocabularies/data/document_experiments.json
cds_ils/vocabularies/data/document_standard_reviews.json
ui/src/config.js

* Adds accelerator, experiments and
standard_reviews vocabularies

vocabulary: Adds document related vocabularies

---

cds_ils/cli.py
scripts/life_data_setup
setup.py

Fix overriding of invenio demo commands

Cli: rename click group for user testing

---

ui/src/config.js

PatronsSearch: search by ccid

---

cds_ils/ldap/api.py
tests/ldap/test_ldap_cli.py

* updates the email of a user if it was changed
* safeguard in case of missing email
* tests
**Note**: the issue of the task being killed was described and fixed in #208

ldap: update email when changed

---

cds_ils/vocabularies/data/alternative_identifier_schemes.json
cds_ils/vocabularies/data/alternative_title_types.json
cds_ils/vocabularies/data/author_identifier_schemes.json
cds_ils/vocabularies/data/author_roles.json
cds_ils/vocabularies/data/currencies.json
cds_ils/vocabularies/data/identifier_schemes.json
cds_ils/vocabularies/data/series_identifier_schemes.json
cds_ils/vocabularies/data/tags.json

Updates vocabularies values according to the librarians response (see [here](https://codimd.web.cern.ch/uR0k-4yiTzW0BSnp7mDw0Q?view#CDS-ILS-Vocabularies))

vocab: Updates vocabularies values

---

cds_ils/cli.py

In `user-testing prepare` command, display error and fail when trying to create the ongoing loan if someone else has an active loan on the item (but the past loan will be created).

Cli: user testing fail if item has active loan

---

cds_ils/config.py
cds_ils/eitems/__init__.py
cds_ils/eitems/serializers/__init__.py
cds_ils/eitems/serializers/csv.py
cds_ils/eitems/serializers/custom_fields.py
cds_ils/eitems/serializers/json.py
cds_ils/literature/serializers/__init__.py
cds_ils/literature/serializers/csv.py
cds_ils/literature/serializers/json.py
tests/api/test_ebook_links.py
tests/conftest.py
tests/data/eitems.json

* serialize the extra field `login_required_url` when `login_required`
is True.
* prefix the protected URL with the EzProxy URL
* partially closes #162

eitems: serialize extra field in response

---

cds_ils/migrator/loans/api.py
requirements.pinned.txt
setup.py

Depends on https://github.com/inveniosoftware/invenio-app-ils/pull/977

anonymous: Updates AnonymousPatron

---

cds_ils/migrator/records.py
cds_ils/migrator/utils.py

migration: fix created_by field for documents

---

ui/src/overridden/components/Menu/RightMenuItem.js

Closes partially inveniosoftware/react-invenio-app-ils#278

HelpMenu: fix external resources link

---

cds_ils/migrator/api.py
cds_ils/migrator/cli.py
cds_ils/migrator/series/api.py

* ~depends on CERNDocumentServer/cds-dojson#273~ :heavy_check_mark: (requires `pip install -e .`)
* ~depends on inveniosoftware/react-invenio-app-ils#304~ :heavy_check_mark:

migration: multipart

---

ui/src/overridableMapping.js
ui/src/overridden/frontsite/Document/DocumentDetails/DocumentCirculation/NotAvailable.js

[Depends on #307@riaILS] LoanRequest: override not available copy list item in frontsite 

---

cds_ils/importer/providers/cds/cds.py
cds_ils/importer/providers/cds/ignore_fields.py
cds_ils/importer/providers/cds/rules/base.py
cds_ils/migrator/DocumentLoader.py
cds_ils/migrator/RecordLoader.py
cds_ils/migrator/eitems/api.py
cds_ils/migrator/series/api.py
tests/migrator/test_books.py

* add ISBN to cover_metadata
* closes #212

migration: fix eitem ebl links migration

---

cds_ils/config.py
cds_ils/importer/admin.py
cds_ils/importer/api.py
cds_ils/importer/cli.py
cds_ils/importer/models.py
cds_ils/importer/views.py
cds_ils/ldap/cli.py
cds_ils/ldap/tasks.py
cds_ils/patrons/permissions.py
setup.py
ui/package-lock.json
ui/package.json
ui/src/config.js
ui/src/overridableMapping.js
ui/src/overridden/api/importer/importer.js
ui/src/overridden/api/importer/index.js
ui/src/overridden/backoffice/Importer/ImportedDocuments.js
ui/src/overridden/backoffice/Importer/Importer.js
ui/src/overridden/backoffice/Importer/ReportDetails.js
ui/src/overridden/backoffice/Importer/index.js
ui/src/overridden/backoffice/Sidebar/SideBarMenuItem.js
ui/src/overridden/routes/BackofficeUrls.js
ui/src/overridden/routes/ImporterRoute.js
ui/src/semantic-ui/site/modules/accordion.overrides

* closes #213
* ~depends on inveniosoftware/react-invenio-app-ils#308~ :heavy_check_mark: 
This new page allows us to import documents slecting the provider, the mode and uploading the file.
- All the fields are required. 
- The file estension must be `.xml`.
- If we select `delete` as mode, a confirmation modal will appear.
- While processing data (importing records), if we try to close/reload the results page we will get an alert.
- Each 30 seconds we will fetch the data (this can be changed).
Some screenshots:

Importer: endpoints and ui

---

cds_ils/config.py
cds_ils/migrator/acquisition/__init__.py
cds_ils/migrator/acquisition/orders.py
cds_ils/migrator/acquisition/vendors.py
cds_ils/migrator/api.py
cds_ils/migrator/cli.py
cds_ils/migrator/document_requests/__init__.py
cds_ils/migrator/document_requests/api.py
cds_ils/migrator/errors.py
cds_ils/migrator/ill/__init__.py
cds_ils/migrator/ill/api.py
cds_ils/migrator/items/api.py
cds_ils/migrator/utils.py
cds_ils/patrons/api.py
cds_ils/vocabularies/data/acq_payment_modes.json
cds_ils/vocabularies/data/currencies.json
cds_ils/vocabularies/data/document_requests_mediums.json
cds_ils/vocabularies/data/ill_item_types.json
scripts/life_data_setup
setup.py

- migrates Vendors
- migrates ILL Borrowing Requests
- migrates Acquisition Orders and OrderLines
- closes #172

migration: acquisition and ILL

---

cds_ils/ldap/api.py
tests/ldap/test_ldap.py

* closes #239
For reviewers: the code changes are only a refactoring to spit that huge function in smaller function (that could be extracted in a class later). I have highlighted the only change that I have added with a comment.

ldap: fix import on duplicated emails

---

ui/src/overridableMapping.js
ui/src/overridden/frontsite/Routes/LegacyRoute.js
ui/src/overridden/routes/ImporterRoute.js

Closes inveniosoftware/react-invenio-app-ils#312

Routes: fix not-found route bug

---

requirements.pinned.txt
setup.py
ui/package-lock.json
ui/package.json
ui/src/overridden/components/Menu/RightMenuItem.js

* Removes deprecated Responsive component
* Blocked by https://github.com/inveniosoftware/react-invenio-app-ils/pull/321
* Blocked by https://github.com/inveniosoftware/react-invenio-app-ils/pull/329

dependencies: Upgrades SUI and minor upgrades

---

cds_ils/cli.py
cds_ils/static_pages/search_guide.html
ui/src/config.js
ui/src/overridden/components/Footer/Footer.js
ui/src/overridden/components/Menu/RightMenuItem.js

* closes inveniosoftware/react-invenio-app-ils#279
Most of the content was copied from Zenodo and adapted to CDS-ILS.
At the bottom of the page I listed all the fields that were relevant: consider deleting the ones that are expected to be removed from the index.
([full size screenshot](https://user-images.githubusercontent.com/9027075/104477856-e3925800-55c1-11eb-94a4-2f35efbbd9d6.png))

pages: search guide

---

ui/src/overridden/components/Menu/Logo.js
ui/src/semantic-ui/site/globals/site.overrides

menu: Fixes responsive menu in mobile devices

---

cds_ils/importer/providers/cds/cds.py
cds_ils/importer/providers/cds/models/journal.py
cds_ils/importer/providers/cds/rules/journal.py
cds_ils/migrator/cli.py
cds_ils/migrator/relations/api.py
cds_ils/migrator/series/__init__.py
cds_ils/migrator/series/api.py
cds_ils/migrator/series/series_import.py
tests/migrator/test_journals.py

Closes CERNDocumentServer/cds-dojson#262

migration: migrate journal relation fields

---

cds_ils/importer/providers/cds/rules/base.py
tests/migrator/test_books.py

rules: Adds relation type other for 962__b

---

cds_ils/importer/XMLRecordToJson.py
cds_ils/importer/providers/cds/cds.py
cds_ils/importer/providers/cds/ignore_fields.py
cds_ils/importer/providers/cds/rules/base.py
cds_ils/migrator/cli.py
cds_ils/migrator/relations/api.py
tests/migrator/test_books.py
tests/migrator/test_relations.py

Closes #283 
Closes https://github.com/orgs/inveniosoftware/projects/19#card-53138088

migration: add relation when journal recid in publication info

---

cds_ils/importer/providers/cds/models/journal.py
cds_ils/importer/providers/cds/rules/base.py
cds_ils/importer/providers/cds/rules/journal.py
tests/migrator/test_books.py
tests/migrator/test_journals.py

Closes CERNDocumentServer/cds-dojson#264
Closes #281
Migrated fields: 85641, 85642, 8654_, 866__

migration: migrate journal urls

---

cds_ils/migrator/acquisition/orders.py
cds_ils/migrator/acquisition/vendors.py
cds_ils/migrator/default_records.py
cds_ils/migrator/ill/api.py
cds_ils/migrator/internal_locations/api.py
cds_ils/migrator/items/utils.py

* legacy_id can be an array or an integer
* Blocked by release of [invenio-app-ils](https://github.com/inveniosoftware/invenio-app-ils/pull/1015)
* closes https://github.com/CERNDocumentServer/cds-ils/issues/280

migration: Updates migration of internal_location

---

cds_ils/patrons/serializers.py
tests/api/test_patrons_views.py

edh: endpoint

---

tests/api/test_patrons_views.py
tests/conftest.py
tests/data/ill_borrowing_requests.json
tests/data/ill_libraries.json
tests/data/loans.json

* Adds ILL test case for EDH endpoint

edh: endpoint test

---

cds_ils/migrator/series/multipart.py
cds_ils/migrator/series/xml_multipart_loader.py

migration: fix multiparts relation indexing

---

MANIFEST.in
cds_ils/migrator/eitems/api.py
cds_ils/migrator/xml_to_json_dump.py

* fix celery and server scripts
* closes #300

migration: fix files loader

---

cds_ils/migrator/cli.py
cds_ils/migrator/items/api.py

migration: fix multiple file sources for items

---

cds_ils/importer/providers/cds/rules/base.py
cds_ils/importer/providers/cds/rules/utils.py
tests/migrator/test_books.py

migration: clean DOI fields

---

cds_ils/importer/providers/safari/importer.py
cds_ils/importer/providers/springer/importer.py

* for springer and safari provided eitems

importer: set open access to false

---

cds_ils/importer/providers/cds/cds.py
cds_ils/importer/providers/cds/models/journal.py
cds_ils/importer/providers/cds/rules/base.py
cds_ils/importer/providers/cds/rules/journal.py
cds_ils/importer/providers/cds/rules/standard.py
cds_ils/importer/providers/cds/rules/utils.py
cds_ils/importer/providers/cds/rules/values_mapping.py
cds_ils/migrator/documents/api.py
cds_ils/migrator/items/api.py
cds_ils/migrator/items/utils.py
cds_ils/vocabularies/data/item_mediums.json
tests/migrator/test_books.py
tests/migrator/test_journals.py

* closes https://github.com/CERNDocumentServer/cds-dojson/issues/259
* Depends on https://github.com/inveniosoftware/invenio-app-ils/pull/1024

migration: Add medium rule to document and journal

---

cds_ils/config.py
cds_ils/importer/providers/cds/rules/base.py
tests/migrator/test_books.py
ui/src/config.js

* Updates extension fields
* Needs https://github.com/inveniosoftware/invenio-app-ils/pull/1032

extension: fields

---

cds_ils/importer/cli.py
cds_ils/importer/series/api.py
cds_ils/importer/series/importer.py
ui/src/config.js

* Fixes series bug, added mathing by title
* Removes cds as a provider in the importer UI
* closes #277
* closes #334

importer: series

---

cds_ils/importer/documents/api.py
cds_ils/importer/providers/cds/importer.py
cds_ils/importer/providers/cds/models/document.py
cds_ils/importer/providers/cds/models/journal.py
cds_ils/importer/providers/cds/models/multipart.py
cds_ils/importer/providers/cds/rules/base.py
cds_ils/importer/providers/cds/rules/utils.py
setup.py
tests/importer/test_provider_matching.py
tests/migrator/test_books.py
tests/migrator/test_model_matcher.py

migration: multiple values in created_by field

---

cds_ils/static_pages/search_guide.html
ui/src/overridden/components/Menu/RightMenuItem.js
ui/src/semantic-ui/site/globals/site.overrides

* Search guide page is responsive now
* Fixed navbar

responsive: fixes

---

cds_ils/cli.py
cds_ils/static_pages/terms.html
ui/src/overridden/components/Footer/Footer.js

update terms page

---

cds_ils/migrator/document_requests/api.py
cds_ils/vocabularies/data/docreq_request_type.json
cds_ils/vocabularies/data/document_requests_mediums.json
cds_ils/vocabularies/data/ill_item_types.json

* add suggestion value in document request types
Closes #329

vocabularies: remove migrated/unknown value

---

ui/src/overridableMapping.js
ui/src/overridden/frontsite/DocumentRequest/DocumentRequestForm.js
ui/src/overridden/frontsite/DocumentRequest/DocumentRequestFormHeader.js
ui/src/semantic-ui/site/globals/site.overrides

* Updates fields
* closes https://github.com/CERNDocumentServer/cds-ils/issues/355

literatureRequest: form

---

cds_ils/importer/providers/cds/rules/journal.py
cds_ils/templates/invenio_app_ils_circulation/mail/cds_request.html
tests/migrator/test_journals.py

* Adds rules to translate the physical_volumes
and electronic_volumes_description fields
* Needs https://github.com/inveniosoftware/invenio-app-ils/pull/1059
* closes https://github.com/CERNDocumentServer/cds-ils/issues/361

[BLOCKED by IAILS#1059] journals: volumes rules

---

cds_ils/migrator/acquisition/orders.py
cds_ils/migrator/document_requests/api.py
cds_ils/migrator/eitems/api.py
cds_ils/migrator/ill/api.py
cds_ils/migrator/providers/api.py
cds_ils/migrator/relations/api.py

* fix document requests legacy pid

migration: fix relations legacy pid

---

cds_ils/importer/providers/cds/rules/base.py
cds_ils/importer/providers/cds/rules/multipart.py
cds_ils/importer/providers/cds/rules/utils.py
cds_ils/migrator/relations/api.py
cds_ils/migrator/series/multipart.py
tests/migrator/rules/test_books.py
tests/migrator/test_fields_utils.py

* Adds rule for 084__c
* Fixes relation between standard and
volumes of multiparts
* closes https://github.com/CERNDocumentServer/cds-migrator-kit/issues/75

standard: rules

---

cds_ils/importer/providers/cds/rules/base.py
cds_ils/importer/providers/cds/rules/multipart.py
cds_ils/migrator/xml_document_loader.py
tests/migrator/rules/test_books.py
tests/migrator/rules/test_series.py

* Fix document rules
* closes https://github.com/CERNDocumentServer/cds-migrator-kit/issues/78
* closes https://github.com/CERNDocumentServer/cds-migrator-kit/issues/79

document: rules

---

cds_ils/migrator/eitems/api.py

* Adds format when importing files
* closes https://github.com/CERNDocumentServer/cds-migrator-kit/issues/82

migration: files

---

cds_ils/migrator/items/utils.py

* Fix rule for item status
* closes https://github.com/CERNDocumentServer/cds-migrator-kit/issues/87

migration: item status

---

ui/src/overridden/frontsite/Home/HomeContent.js

prettier: fix

---

cds_ils/migrator/ill/api.py

* Adds fallback provider to borrowing
requests migration
* closes https://github.com/CERNDocumentServer/cds-migrator-kit/issues/102

migration: ill

---

cds_ils/importer/providers/cds/models/journal.py
cds_ils/importer/providers/cds/rules/base.py
cds_ils/importer/providers/cds/rules/journal.py
cds_ils/migrator/consts.py
cds_ils/migrator/json_record_loader.py
cds_ils/migrator/series/api.py
cds_ils/migrator/series/xml_series_loader.py
cds_ils/migrator/xml_document_loader.py
tests/migrator/rules/test_journals.py
tests/migrator/xml_imports/test_migrate_journal.py

* Adds created date to series
* Overrides _created rule for journals
* closes https://github.com/CERNDocumentServer/cds-migrator-kit/issues/100

migration: series

---

cds_ils/importer/providers/cds/rules/journal.py
tests/migrator/rules/test_journals.py
tests/migrator/xml_imports/test_migrate_journal.py

* Fixes rules for access_rules of journals
* closes https://github.com/CERNDocumentServer/cds-migrator-kit/issues/97

migration: journal

---

cds_ils/importer/providers/cds/cds.py
cds_ils/importer/providers/cds/rules/base.py
cds_ils/importer/providers/cds/rules/values_mapping.py
cds_ils/migrator/eitems/api.py
tests/migrator/rules/test_books.py
tests/migrator/xml_imports/test_migrate_document.py
tests/migrator/xml_imports/test_migrate_proceedings.py
tests/migrator/xml_imports/test_migrate_standard.py

* Adds 595__a as internal_note for eitems
* closes https://github.com/CERNDocumentServer/cds-migrator-kit/issues/107

migration: eitem

---

cds_ils/config.py
cds_ils/importer/providers/cds/models/document.py
cds_ils/importer/providers/cds/rules/base.py
cds_ils/importer/providers/cds/rules/values_mapping.py
cds_ils/importer/providers/utils.py
cds_ils/migrator/documents/xml_document_loader.py
tests/migrator/rules/test_books.py
tests/migrator/xml_imports/test_migrate_proceedings.py
ui/src/config.js

* Ignored fields
* Updated rules
* https://github.com/CERNDocumentServer/cds-migrator-kit/issues/108

migration: document fixes

---

ui/src/overridden/frontsite/Home/Slogan.js

Closes https://github.com/CERNDocumentServer/cds-migrator-kit/issues/124

ui: change slogan text

---

cds_ils/config.py
cds_ils/eitems/serializers/json.py
cds_ils/importer/providers/cds/rules/journal.py
cds_ils/literature/serializers/csv.py
cds_ils/literature/serializers/json.py
cds_ils/migrator/eitems/api.py
cds_ils/series/__init__.py
cds_ils/series/serializers/__init__.py
cds_ils/series/serializers/csv.py
cds_ils/series/serializers/json.py
cds_ils/utils.py
tests/migrator/rules/test_journals.py
tests/migrator/xml_imports/test_migrate_journal.py
tests/migrator/xml_imports/test_migrate_multivolume.py

Depends on https://github.com/inveniosoftware/invenio-app-ils/pull/1077

[BLOCKED]migration: migrate login_required for series

---

cds_ils/ldap/api.py
tests/ldap/test_ldap.py
tests/migrator/rules/test_books.py

ldap: sync non cern emails

---

cds_ils/literature/covers.py
cds_ils/series/serializers/json.py

serializers: fix series covers

---

cds_ils/templates/invenio_app_ils/mail/cds_footer.html
cds_ils/templates/invenio_app_ils_circulation/mail/cds_cancel.html
cds_ils/templates/invenio_app_ils_circulation/mail/cds_checkin.html
cds_ils/templates/invenio_app_ils_circulation/mail/cds_checkout.html
cds_ils/templates/invenio_app_ils_circulation/mail/cds_extend.html
cds_ils/templates/invenio_app_ils_circulation/mail/cds_overdue_reminder.html
cds_ils/templates/invenio_app_ils_circulation/mail/cds_request.html
cds_ils/templates/invenio_app_ils_circulation/mail/cds_request_no_items.html
cds_ils/templates/invenio_app_ils_circulation/mail/cds_will_expire_in_reminder.html

email: modify templates

---

cds_ils/literature/views.py
ui/package-lock.json
ui/package.json

* backend: fix redirection on deleted legacy pid

ui: update react-searchkit version

---

cds_ils/ldap/api.py
cds_ils/ldap/client.py
cds_ils/ldap/errors.py
cds_ils/ldap/serializers.py
cds_ils/ldap/user_importer.py
cds_ils/patrons/api.py
tests/ldap/test_ldap.py
ui/src/config.js
ui/src/overridden/backoffice/PatronMetadata/PatronMetadata.js

ldap: add patrons mailbox

---

cds_ils/config.py
cds_ils/importer/api.py
cds_ils/importer/eitems/importer.py
cds_ils/importer/errors.py
cds_ils/importer/importer.py
cds_ils/importer/models.py
cds_ils/importer/providers/cds/importer.py
cds_ils/importer/providers/cds/rules/base.py
cds_ils/importer/providers/ebl/rules/document.py
cds_ils/importer/tasks.py
cds_ils/importer/views.py
cds_ils/vocabularies/data/eitem_sources.json
requirements.pinned.txt
setup.py
ui/package-lock.json
ui/package.json
ui/src/api/importer/importer.js
ui/src/importer/ImporterList.js
ui/src/importer/importerTaskDetails/ImportedDocumentReport.js
ui/src/importer/importerTaskDetails/ImportedDocuments.js
ui/src/importer/importerTaskDetails/cancelImportTask.js

for reviewers, only 1 commit:
https://github.com/CERNDocumentServer/cds-ils/pull/577/commits/ea7c3c0b624a64429b5210c96ddca43160b3eaeb
* addresses #557 
* closes #567

importer: cancel current import

---

ui/package-lock.json
ui/package.json
ui/src/config.js

Select Physical copy as the default value of the type in the borrowing requests form.
closes https://github.com/CERNDocumentServer/cds-ils/issues/327

[DEP:RIAILS] Borrowing form adjustment

---

setup.py
ui/src/overridden/backoffice/PatronMetadata/PatronMetadata.js
ui/src/overridden/components/Footer/Footer.js
ui/src/overridden/components/Menu/Logo.js
ui/src/overridden/frontsite/Routes/LegacyRoute.js
ui/src/semantic-ui/site/globals/site.overrides

Improve logo and footer

---

cds_ils/static_pages/search_guide.html

**TODO**
pages need to be repopulated after this change otherwise the changes will not be visible
closes https://github.com/CERNDocumentServer/cds-ils/issues/574

search guide: examples updated

---

cds_ils/vocabularies/data/eitem_sources.json

* Add the sources proposed by the librarians to the ones already available when creating an EItem.
* closes: CERNDocumentServer#607

EItem: Add aditional sources.

---

cds_ils/vocabularies/data/acq_order_line_payment_modes.json

acquisition: change payment mode vocabulary

---

cds_ils/importer/api.py
cds_ils/importer/documents/api.py
cds_ils/importer/eitems/importer.py
cds_ils/importer/importer.py
cds_ils/importer/providers/ebl/rules/document.py
cds_ils/importer/providers/safari/rules/document.py
cds_ils/importer/providers/springer/rules/document.py
cds_ils/importer/providers/springer/springer.py
cds_ils/importer/providers/utils.py
cds_ils/importer/series/api.py
cds_ils/importer/series/importer.py
cds_ils/literature/api.py
cds_ils/migrator/items/utils.py
cds_ils/vocabularies/data/acq_order_line_payment_modes.json
requirements.pinned.txt
setup.py
tests/importer/test_ebl_dojson.py
tests/importer/test_springer_dojson.py
ui/src/importer/EitemImportDetailsModal/EitemImportDetailsModal.js
ui/src/importer/SeriesImportDetailsModal/SeriesImportDetailsModal.js
ui/src/importer/importerTaskDetails/ImportedDocumentReport.js

* add proper eitem PIDs deletion
* fix duplicated series display
* close #652

[DEPENDS ON ILS] importer: match lowercase titles

---

cds_ils/importer/errors.py
cds_ils/importer/importer.py
cds_ils/importer/series/importer.py
setup.py
ui/src/importer/importerTaskDetails/ImportedDocumentReport.js
ui/src/importer/importerTaskDetails/ImportedDocuments.js

Fix "has only serial relations" check. In the past there was a check for making sure a record had only serial relations (if any), but, instead of checking that all the relations that it had were serial, it was checking that it had relations AND they were serial. This was fixed to aim for it's true purpose.
Raise errors in preview delete. In the past, in preview delete mode, we would mark a record as "delete" if it didn't had any non serial relations; meanwhile in real delete, we would try to delete it anyways and raise and exception if there was any problem due to this relations, now the behaviour in the preview delete has been changed so it can raise the same exceptions. 
Fix inconsistency in preview statuses. In the past, in delete mode, the importer would try to delete the record even …

Importer: fix inconsistency in preview statuses 

---

cds_ils/config.py
cds_ils/importer/eitems/importer.py
cds_ils/importer/importer.py
ui/src/config.js

importer: fix eitem search

---

ui/src/importer/importerTaskDetails/ImportedDocuments.js

Now shows the status code and error message when an error is returned on the task details page

Import: nuanced errors on task page

---

cds_ils/importer/serializers/schema.py
ui/src/importer/importerTaskDetails/ImporterTaskDetails.js

Importer does not send requests anymore before a request is done
closes https://github.com/CERNDocumentServer/cds-ils/issues/675

Importer: performance improvements 

---

cds_ils/importer/eitems/importer.py
cds_ils/importer/importer.py
cds_ils/importer/providers/cds/helpers/eitems.py
cds_ils/importer/providers/ebl/rules/document.py
cds_ils/importer/providers/safari/rules/document.py
cds_ils/importer/providers/springer/rules/document.py
tests/importer/data/existing_documents.json
tests/importer/data/existing_eitems.json
tests/importer/test_ebl_dojson.py
tests/importer/test_eitem_priorities.py
tests/importer/test_safari_dojson.py
tests/importer/test_springer_dojson.py
tests/migrator/rules/test_series.py

* unify the URL description
* closes #659
* partially addresses RQF1946420

importer: add tests for providers priority

---

cds_ils/importer/api.py
cds_ils/importer/documents/importer.py
cds_ils/importer/errors.py
tests/importer/test_document_matching.py

* fix efition matching
* closes #686
* partially addresses RQF1946580

importer: handle unavailable similarity match

---

cds_ils/importer/documents/api.py
requirements.pinned.txt
setup.py

importer: document match by authors full names

---

cds_ils/importer/importer.py

* address ConflictError on referenced records

importer: improve the indexing after import

---

cds_ils/importer/providers/ebl/rules/document.py
cds_ils/importer/providers/springer/rules/document.py

* replace "series" only on the end of the serial title
* close #RQF1946586

importer: fix parse and clean series title

---

cds_ils/importer/eitems/importer.py
cds_ils/importer/models.py
ui/package-lock.json
ui/package.json

* fix previewer missing document pid

global: upgrade react-invenio-app-ils

---

cds_ils/importer/XMLRecordToJson.py
cds_ils/importer/errors.py
cds_ils/importer/handlers.py
cds_ils/importer/providers/cds/rules/base.py
cds_ils/importer/providers/cds/rules/journal.py
cds_ils/importer/providers/cds/rules/multipart.py
cds_ils/importer/providers/cds/rules/standard.py
cds_ils/importer/providers/cds/rules/values_mapping.py
cds_ils/importer/providers/ebl/rules/document.py
cds_ils/importer/providers/safari/rules/document.py
cds_ils/importer/providers/springer/rules/document.py
cds_ils/importer/providers/utils.py

importer: improve error handling

---

cds_ils/importer/XMLRecordToJson.py
cds_ils/importer/api.py
cds_ils/importer/documents/importer.py
cds_ils/importer/eitems/importer.py
cds_ils/importer/handlers.py
cds_ils/importer/importer.py

importer: add exception handlers

---

cds_ils/circulation/indexer.py

Ensure application handles reindexing records related to a deleted document.
Issue appeared when reinxeding a document (and it's records) that was very recently deleted.
Add additional comments explaining rationale behind implementation of item_suggestion.

Documents: check if document exists when indexing

---

cds_ils/cli.py
cds_ils/static_pages/privacy_policy.html
ui/src/config.js
ui/src/overridden/components/Footer/Footer.js

* closes #490
I have already fixed the spelling errors.

Footer: add privacy policy page

---

ui/src/importer/importerTaskDetails/ImportedDocuments.js
ui/src/importer/importerTaskDetails/ImporterTaskDetailsComponents/ImportStats.js
ui/src/importer/importerTaskDetails/ImporterTaskDetailsComponents/ImportedDocumentReport.js

partly closes https://github.com/CERNDocumentServer/cds-ils/issues/685

Importer: Partial matches overflowing

---

cds_ils/circulation/indexer.py
cds_ils/circulation/serializers/__init__.py

circulation: item suggestion for pending loans

---

cds_ils/importer/documents/importer.py
requirements.pinned.txt
setup.py

importer: validate serial volumes

---

cds_ils/importer/series/importer.py
cds_ils/notifications/templates/cds_ils_notifications/cds_ils_user_deletion_warning_active_loans.html

* importer: fix series matches validation

anonymization alert: fix email content

---

cds_ils/importer/eitems/importer.py
cds_ils/importer/importer.py
setup.py
ui/src/overridden/frontsite/Document/DocumentDetails/DocumentCirculation/LiteratureKeyword.js

* special case: the importer provider can be manually changed after an
import and it might be not one of the configured.

importer: fix provider priority

---

cds_ils/vocabularies/data/acq_order_line_payment_modes.json

* add vocabulary option for mapping fix
* closes https://github.com/inveniosoftware/react-invenio-app-ils/issues/352

form prefilling: vocabulary fix

---

ui/src/overridden/frontsite/Document/DocumentDetails/DocumentMetadataTabs/Identifiers/Identifiers.js

* remove unnecessary quotes
* closes https://github.com/inveniosoftware/react-invenio-app-ils/issues/550

Literature details page: the identifiers tab

---

.github/workflows/tests.yml
setup.cfg
ui/src/overridden/frontsite/LiteratureSearch/SearchResultExtra.js

Change headline

---

scripts/setup

Fix for the following error:
```console
127.0.0.1 - - [13/Dec/2023 15:12:16] "GET /api/oauth/login/cern_openid/?next=%2F HTTP/1.1" 302 -
127.0.0.1 - - [13/Dec/2023 15:12:34] "GET /api/oauth/authorized/cern_openid/<REDACTED>" 302 -
[2023-12-13 15:12:36,163] ERROR in app: Exception on /me [GET]
Traceback (most recent call last):
File "/Users/saksham/.virtualenvs/cds-ils-test/lib/python3.6/site-packages/flask/app.py", line 2073, in wsgi_app
response = self.full_dispatch_request()
File "/Users/saksham/.virtualenvs/cds-ils-test/lib/python3.6/site-packages/flask/app.py", line 1518, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/Users/saksham/.virtualenvs/cds-ils-test/lib/python3.6/site-packages/flask_cors/extension.py", line 176, in wrapped_function
return …
```

Create library location in demo data in setup step

---

ui/src/overridden/backoffice/PatronMetadata/PatronMetadata.js

backoffice: PatronMetadata: query cern phonebook on email and not person_id

---

cds_ils/importer/documents/api.py
cds_ils/importer/documents/importer.py
cds_ils/importer/series/importer.py
tests/importer/data/match_testing_documents.json
tests/importer/data/match_testing_series.json
tests/importer/test_document_matching.py
tests/importer/test_series_matching.py

importer: Fix normalized title matching for documents and series

---

cds_ils/config.py
cds_ils/importer/errors.py
cds_ils/importer/providers/cds/helpers/decorators.py
cds_ils/importer/providers/cds/rules/base.py
cds_ils/migrator/eitems/api.py
tests/migrator/test_utils.py
ui/src/config.js

Closes: https://github.com/CERNDocumentServer/cds-ils/issues/835

config: Set loan request startdate to be 2 days from current date

---

cds_ils/vocabularies/data/tags.json

Resolves: #824 
```sh
bash -c "invenio vocabulary index json --force cds_ils/vocabularies/data/tags.json"
```

vocabularies: tags: Add Yellow Report, Women in Tech and Diversity tags

---

ui/src/config.js

config: Rename borrowReq 'Returned Date' -> 'Returned date'

---

cds_ils/importer/XMLRecordToJson.py
cds_ils/importer/providers/cds/rules/values_mapping.py
cds_ils/importer/providers/safari/rules/document.py
cds_ils/importer/providers/safari/safari.py
tests/importer/data/documents_with_audiobook.json
tests/importer/data/existing_documents.json
tests/importer/data/existing_eitems.json
tests/importer/data/safari_audiobook.xml
tests/importer/test_ebl_dojson.py
tests/importer/test_importer.py
tests/importer/test_safari_dojson.py

importer: Add ability to import audiobooks

---

cds_ils/config.py
cds_ils/patrons/permissions.py
ui/src/config.js

config: Update checkout permissions to support self checkout

---

cds_ils/config.py
requirements.pinned.txt
setup.cfg
ui/package-lock.json
ui/package.json

config: use AND query parser instead of default operator OR

---

cds_ils/config.py
cds_ils/items/__init__.py
cds_ils/items/loaders.py
ui/src/config.js

items: Add call number validation to ItemSchema

---

ui/src/overridden/frontsite/Document/DocumentDetails/DocumentCirculationExtras.js
ui/src/overridden/utils.js

overridden: DocumentDetails: Add InfoPopup when item has no shelf

---

cds_ils/importer/series/importer.py

* closes https://github.com/CERNDocumentServer/cds-ils/issues/923

serials importer: remove substrings only from the end of the title

---

cds_ils/config.py
cds_ils/templates/invenio_app_ils_circulation/notifications/cds_self_checkout.html
setup.cfg

Requires:
- UI: https://github.com/inveniosoftware/react-invenio-app-ils/pull/649
- Backend: https://github.com/inveniosoftware/invenio-app-ils/pull/1223
Closes: https://github.com/CERNDocumentServer/cds-ils/issues/927

self-checkout: add new template

---

ui/src/overridden/frontsite/Document/DocumentDetails/DocumentItemsHeader.js
ui/src/overridden/frontsite/Home/HomeContent.js
ui/src/overridden/frontsite/LiteratureSearch/SearchResultExtra.js
ui/src/overridden/frontsite/LiteratureSearch/SearchResultHeader.js
ui/src/overridden/utils.js

* Requested in https://cern.service-now.com/service-portal?id=ticket&table=u_request_fulfillment&n=RQF3021542

frontsite: update display of snv link

---

ui/src/overridden/frontsite/Document/DocumentDetails/DocumentItemsHeader.js

* requested by https://cern.service-now.com/nav_to.do?uri=u_request_fulfillment.do?sysparm_query=number=RQF3021542

frontsite: Update standard snv message

---

ui/src/config.js

Closes: https://github.com/CERNDocumentServer/cds-ils/issues/981

ui: turned shelf field into search in item form

---

ui/src/config.js
ui/src/overridden/frontsite/Document/DocumentDetails/DocumentItemBody.js

closes: https://github.com/CERNDocumentServer/cds-ils/issues/956

ui: moved call number into its own column

---

cds_ils/cli.py
setup.cfg

depends on: https://github.com/CERNDocumentServer/cds-ils/pull/1014

fixtures: fix cds fixtures being overwritten by invenio-app-ils fixtures
